# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.TextField(max_length=30)),
                ('listDesc', models.TextField(max_length=20)),
                ('listCompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.TextField(max_length=30)),
                ('listDesc', models.TextField(max_length=50)),
                ('listDueDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='listId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoApp.ToDoList'),
        ),
    ]
