# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='listCompleted',
            new_name='itemCompleted',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='listDesc',
            new_name='itemDesc',
        ),
    ]
